function(setup_sanitizers project_options)
    if (CMAKE_CXX_COMPILER_ID MATCHES ".*Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${project_options} INTERFACE -fsanitize=address,undefined)
        target_link_options(${project_options} INTERFACE -fsanitize=address,undefined)
    else ()
        target_compile_options(${project_options} INTERFACE $<$<CXX_COMPILER_ID:MSVC>:/fsanitize=address /Zi /INCREMENTAL:NO>)
        target_compile_definitions(${project_options} INTERFACE _DISABLE_VECTOR_ANNOTATION _DISABLE_STRING_ANNOTATION)
        target_link_options(${project_options} INTERFACE /INCREMENTAL:NO)
    endif ()
endfunction()